using UnityEngine;
using UnityEngine.UI;
using PixelCrushers.DialogueSystem;
using Manager.Inventory;
using Manager.UI;

public class BananaQuestObject : MonoBehaviour
{
    //private string inventoryManagerMethodPickupItem = "PickupItem";
    private string questTitle = "BananaQuest";
    //private string inventoryYManagerMethodUpdateItemIcon = "UpdateItemIcon";
    private QuestState newQuestState = QuestState.Success;
    public GameObject questObject;
    public string message;
    public Image bananaIcon;
    public InventoryManager inventoryManager;
    public UIManager uiManager;
    public void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            uiManager.SendMessage("UpdateItemIcon");
            QuestLog.SetQuestState(questTitle, newQuestState);
            DialogueManager.ShowAlert(message);
            questObject.SetActive(false);
            //uiManager.
        }
    }
}
